name: tentura
description: 'Social network for communities'
publish_to: 'none'

version: 0.6.11

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  nil: ^1.1.1
  intl: ^0.19.0
  equatable: ^2.0.5
  go_router: ^14.2.3
  collection: ^1.18.0
  built_value: ^8.9.2
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  # Platform related
  hive: ^2.2.3
  geocoding: ^3.0.0
  share_plus: ^10.0.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  mobile_scanner: ^5.1.1
  package_info_plus: ^8.0.2
  flutter_secure_storage: ^9.2.2

  # UI related
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_svg: ^2.0.10
  dots_indicator: ^3.0.0
  pretty_qr_code: ^3.3.0
  vector_graphics: ^1.1.11
  cached_network_image: ^3.4.0
  flutter_native_splash: ^2.4.0
  force_directed_graphview: ^0.6.2

  # Logging & etc
  # logger: ^2.4.0
  # logging: ^1.2.0
  # sentry_link: ^0.4.0
  sentry_flutter: ^8.7.0
  # sentry_logging: ^7.8.0
  # logging_appenders: ^1.1.0

  # Local
  tentura_sdk:
    path: packages/tentura_sdk

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  ferry_generator: ^0.12.0
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/intro/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  ignore_missing: true

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/logo1024.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash_light.png"
  color_dark: "#3A1E5C"
  image_dark: "assets/images/splash_dark.png"
  # background_image_dark: "assets/images/background_dark.png"
