name: gravity
description: 'Gravity for a social ranking'
publish_to: 'none'

version: 0.3.5+0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  url_strategy: ^0.2.0
  flutter_bloc: ^8.1.3
  go_router: ^11.1.4
  equatable: ^2.0.5
  get_it: ^7.6.4
  intl: ^0.18.1

  flutter_secure_storage: ^9.0.0
  ferry_hive_store: ^0.5.1
  ed25519_edwards: ^0.3.1
  ferry_flutter: ^0.8.1
  fresh_graphql: ^0.6.0
  gql_http_link: ^1.0.1
  hive_flutter: ^1.1.0
  built_value: ^8.6.3
  ferry: ^0.14.2
  http: ^1.1.0

  force_directed_graphview: ^0.1.0
  flutter_expandable_fab: ^2.0.0
  cached_network_image: ^3.3.0
  vector_graphics: ^1.1.9
  mobile_scanner: ^3.4.1
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  flutter_map: ^6.0.0
  flutter_svg: ^2.0.7
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  geocoding: ^2.1.1
  latlong2: ^0.9.0
  # image: ^4.0.17

  sentry_flutter: ^7.10.1
  sentry_dart_plugin: ^1.6.0
  # logging_appenders: ^1.1.0
  # sentry_logging: ^7.8.0
  # sentry_link: ^0.3.0
  # logging: ^1.2.0

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  ferry_generator: ^0.8.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  ignore_missing: true
